#include "int_stubs.h"

__attribute__((interrupt))
void common(InterruptFrame* frame) {
    int_disable();
    int_isr_stub(frame, 0xFF);
    __asm__("hlt");
}

void int_stub_register_all() {
    REG_ISR_STUB(0x00);         // #DE Divide by 0
    REG_ISR_STUB(0x01);         // #DB Debug
    REG_ISR_STUB(0x02);         // Non-maskable interrupt
    REG_ISR_STUB(0x03);         // #BP Breakpoint
    REG_ISR_STUB(0x04);         // #OF Overflow
    REG_ISR_STUB(0x05);         // #BR Bound range exceeded
    REG_ISR_STUB(0x06);         // #UD Invalid opcode
    REG_ISR_STUB(0x07);         // #NM Device not available
    REG_ISR_ERR_STUB(0x08);     // #DF Double fault (also default hardware timer, but will remap)
    REG_ISR_STUB(0x09);         // Coprocessor segment overrun
    REG_ISR_ERR_STUB(0x0A);     // #TS Invalid TSS
    REG_ISR_ERR_STUB(0x0B);     // #NP Segment not present
    REG_ISR_ERR_STUB(0x0C);     // #SS Stack-segment fault
    REG_ISR_ERR_STUB(0x0D);     // #GP General protection fault
    REG_ISR_ERR_STUB(0x0E);     // #PF Page fault
    REG_ISR_STUB(0x0F);         // Reserved
    REG_ISR_STUB(0x10);         // #MF x87 FP exception
    REG_ISR_ERR_STUB(0x11);     // #AC Alignment check
    REG_ISR_STUB(0x12);         // #MC Machine check
    REG_ISR_STUB(0x13);         // #XM/#XF SIMD Floating-point exception
    REG_ISR_STUB(0x14);         // #VE Virtualization exception
    REG_ISR_STUB(0x15);         // #CP Control protection exception
    REG_ISR_STUB(0x16);         // Reserved
    REG_ISR_STUB(0x17);         // Reserved
    REG_ISR_STUB(0x18);         // Reserved
    REG_ISR_STUB(0x19);         // Reserved
    REG_ISR_STUB(0x1A);         // Reserved
    REG_ISR_STUB(0x1B);         // Reserved
    REG_ISR_STUB(0x1C);         // #HV Hypervisor injection exception
    REG_ISR_STUB(0x1D);         // #VC VMM communication exception
    REG_ISR_ERR_STUB(0x1E);     // #SX Security exception
    REG_ISR_STUB(0x1F);         // Reserved

    // Hardware interrupts (IRQs)
    REG_ISR_STUB(0x20);
    REG_ISR_STUB(0x21);
    REG_ISR_STUB(0x22);
    REG_ISR_STUB(0x23);
    REG_ISR_STUB(0x24);
    REG_ISR_STUB(0x25);
    REG_ISR_STUB(0x26);
    REG_ISR_STUB(0x27);
    REG_ISR_STUB(0x28);
    REG_ISR_STUB(0x29);
    REG_ISR_STUB(0x2A);
    REG_ISR_STUB(0x2B);
    REG_ISR_STUB(0x2C);
    REG_ISR_STUB(0x2D);
    REG_ISR_STUB(0x2E);
    REG_ISR_STUB(0x2F);

    // REG_ISR_STUB(0xF9);
    // Remaining ISR stubs (0x30-0xFF)
    REG_ISR_STUB(0x30); REG_ISR_STUB(0x31); REG_ISR_STUB(0x32); REG_ISR_STUB(0x33);
    REG_ISR_STUB(0x34); REG_ISR_STUB(0x35); REG_ISR_STUB(0x36); REG_ISR_STUB(0x37);
    REG_ISR_STUB(0x38); REG_ISR_STUB(0x39); REG_ISR_STUB(0x3A); REG_ISR_STUB(0x3B);
    REG_ISR_STUB(0x3C); REG_ISR_STUB(0x3D); REG_ISR_STUB(0x3E); REG_ISR_STUB(0x3F);
    REG_ISR_STUB(0x40); REG_ISR_STUB(0x41); REG_ISR_STUB(0x42); REG_ISR_STUB(0x43);
    REG_ISR_STUB(0x44); REG_ISR_STUB(0x45); REG_ISR_STUB(0x46); REG_ISR_STUB(0x47);
    REG_ISR_STUB(0x48); REG_ISR_STUB(0x49); REG_ISR_STUB(0x4A); REG_ISR_STUB(0x4B);
    REG_ISR_STUB(0x4C); REG_ISR_STUB(0x4D); REG_ISR_STUB(0x4E); REG_ISR_STUB(0x4F);
    REG_ISR_STUB(0x50); REG_ISR_STUB(0x51); REG_ISR_STUB(0x52); REG_ISR_STUB(0x53);
    REG_ISR_STUB(0x54); REG_ISR_STUB(0x55); REG_ISR_STUB(0x56); REG_ISR_STUB(0x57);
    REG_ISR_STUB(0x58); REG_ISR_STUB(0x59); REG_ISR_STUB(0x5A); REG_ISR_STUB(0x5B);
    REG_ISR_STUB(0x5C); REG_ISR_STUB(0x5D); REG_ISR_STUB(0x5E); REG_ISR_STUB(0x5F);
    REG_ISR_STUB(0x60); REG_ISR_STUB(0x61); REG_ISR_STUB(0x62); REG_ISR_STUB(0x63);
    REG_ISR_STUB(0x64); REG_ISR_STUB(0x65); REG_ISR_STUB(0x66); REG_ISR_STUB(0x67);
    REG_ISR_STUB(0x68); REG_ISR_STUB(0x69); REG_ISR_STUB(0x6A); REG_ISR_STUB(0x6B);
    REG_ISR_STUB(0x6C); REG_ISR_STUB(0x6D); REG_ISR_STUB(0x6E); REG_ISR_STUB(0x6F);
    REG_ISR_STUB(0x70); REG_ISR_STUB(0x71); REG_ISR_STUB(0x72); REG_ISR_STUB(0x73);
    REG_ISR_STUB(0x74); REG_ISR_STUB(0x75); REG_ISR_STUB(0x76); REG_ISR_STUB(0x77);
    REG_ISR_STUB(0x78); REG_ISR_STUB(0x79); REG_ISR_STUB(0x7A); REG_ISR_STUB(0x7B);
    REG_ISR_STUB(0x7C); REG_ISR_STUB(0x7D); REG_ISR_STUB(0x7E); REG_ISR_STUB(0x7F);
    REG_ISR_STUB(0x80); REG_ISR_STUB(0x81); REG_ISR_STUB(0x82); REG_ISR_STUB(0x83);
    REG_ISR_STUB(0x84); REG_ISR_STUB(0x85); REG_ISR_STUB(0x86); REG_ISR_STUB(0x87);
    REG_ISR_STUB(0x88); REG_ISR_STUB(0x89); REG_ISR_STUB(0x8A); REG_ISR_STUB(0x8B);
    REG_ISR_STUB(0x8C); REG_ISR_STUB(0x8D); REG_ISR_STUB(0x8E); REG_ISR_STUB(0x8F);
    REG_ISR_STUB(0x90); REG_ISR_STUB(0x91); REG_ISR_STUB(0x92); REG_ISR_STUB(0x93);
    REG_ISR_STUB(0x94); REG_ISR_STUB(0x95); REG_ISR_STUB(0x96); REG_ISR_STUB(0x97);
    REG_ISR_STUB(0x98); REG_ISR_STUB(0x99); REG_ISR_STUB(0x9A); REG_ISR_STUB(0x9B);
    REG_ISR_STUB(0x9C); REG_ISR_STUB(0x9D); REG_ISR_STUB(0x9E); REG_ISR_STUB(0x9F);
    REG_ISR_STUB(0xA0); REG_ISR_STUB(0xA1); REG_ISR_STUB(0xA2); REG_ISR_STUB(0xA3);
    REG_ISR_STUB(0xA4); REG_ISR_STUB(0xA5); REG_ISR_STUB(0xA6); REG_ISR_STUB(0xA7);
    REG_ISR_STUB(0xA8); REG_ISR_STUB(0xA9); REG_ISR_STUB(0xAA); REG_ISR_STUB(0xAB);
    REG_ISR_STUB(0xAC); REG_ISR_STUB(0xAD); REG_ISR_STUB(0xAE); REG_ISR_STUB(0xAF);
    REG_ISR_STUB(0xB0); REG_ISR_STUB(0xB1); REG_ISR_STUB(0xB2); REG_ISR_STUB(0xB3);
    REG_ISR_STUB(0xB4); REG_ISR_STUB(0xB5); REG_ISR_STUB(0xB6); REG_ISR_STUB(0xB7);
    REG_ISR_STUB(0xB8); REG_ISR_STUB(0xB9); REG_ISR_STUB(0xBA); REG_ISR_STUB(0xBB);
    REG_ISR_STUB(0xBC); REG_ISR_STUB(0xBD); REG_ISR_STUB(0xBE); REG_ISR_STUB(0xBF);
    REG_ISR_STUB(0xC0); REG_ISR_STUB(0xC1); REG_ISR_STUB(0xC2); REG_ISR_STUB(0xC3);
    REG_ISR_STUB(0xC4); REG_ISR_STUB(0xC5); REG_ISR_STUB(0xC6); REG_ISR_STUB(0xC7);
    REG_ISR_STUB(0xC8); REG_ISR_STUB(0xC9); REG_ISR_STUB(0xCA); REG_ISR_STUB(0xCB);
    REG_ISR_STUB(0xCC); REG_ISR_STUB(0xCD); REG_ISR_STUB(0xCE); REG_ISR_STUB(0xCF);
    REG_ISR_STUB(0xD0); REG_ISR_STUB(0xD1); REG_ISR_STUB(0xD2); REG_ISR_STUB(0xD3);
    REG_ISR_STUB(0xD4); REG_ISR_STUB(0xD5); REG_ISR_STUB(0xD6); REG_ISR_STUB(0xD7);
    REG_ISR_STUB(0xD8); REG_ISR_STUB(0xD9); REG_ISR_STUB(0xDA); REG_ISR_STUB(0xDB);
    REG_ISR_STUB(0xDC); REG_ISR_STUB(0xDD); REG_ISR_STUB(0xDE); REG_ISR_STUB(0xDF);
    REG_ISR_STUB(0xE0); REG_ISR_STUB(0xE1); REG_ISR_STUB(0xE2); REG_ISR_STUB(0xE3);
    REG_ISR_STUB(0xE4); REG_ISR_STUB(0xE5); REG_ISR_STUB(0xE6); REG_ISR_STUB(0xE7);
    REG_ISR_STUB(0xE8); REG_ISR_STUB(0xE9); REG_ISR_STUB(0xEA); REG_ISR_STUB(0xEB);
    REG_ISR_STUB(0xEC); REG_ISR_STUB(0xED); REG_ISR_STUB(0xEE); REG_ISR_STUB(0xEF);
    REG_ISR_STUB(0xF0); REG_ISR_STUB(0xF1); REG_ISR_STUB(0xF2); REG_ISR_STUB(0xF3);
    REG_ISR_STUB(0xF4); REG_ISR_STUB(0xF5); REG_ISR_STUB(0xF6); REG_ISR_STUB(0xF7);
    REG_ISR_STUB(0xF8); REG_ISR_STUB(0xF9); REG_ISR_STUB(0xFA); REG_ISR_STUB(0xFB);
    REG_ISR_STUB(0xFC); REG_ISR_STUB(0xFD); REG_ISR_STUB(0xFE); REG_ISR_STUB(0xFF);
}

DEF_ISR_STUB(0x00);         // #DE Divide by 0
DEF_ISR_STUB(0x01);         // #DB Debug
DEF_ISR_STUB(0x02);         // Non-maskable interrupt
DEF_ISR_STUB(0x03);         // #BP Breakpoint
DEF_ISR_STUB(0x04);         // #OF Overflow
DEF_ISR_STUB(0x05);         // #BR Bound range exceeded
DEF_ISR_STUB(0x06);         // #UD Invalid opcode
DEF_ISR_STUB(0x07);         // #NM Device not available
DEF_ISR_ERR_STUB(0x08);     // #DF Double fault (also default hardware timer, but will remap)
DEF_ISR_STUB(0x09);         // Coprocessor segment overrun
DEF_ISR_ERR_STUB(0x0A);     // #TS Invalid TSS
DEF_ISR_ERR_STUB(0x0B);     // #NP Segment not present
DEF_ISR_ERR_STUB(0x0C);     // #SS Stack-segment fault
DEF_ISR_ERR_STUB(0x0D);     // #GP General protection fault
DEF_ISR_ERR_STUB(0x0E);     // #PF Page fault
DEF_ISR_STUB(0x0F);         // Reserved
DEF_ISR_STUB(0x10);         // #MF x87 FP exception
DEF_ISR_ERR_STUB(0x11);     // #AC Alignment check
DEF_ISR_STUB(0x12);         // #MC Machine check
DEF_ISR_STUB(0x13);         // #XM/#XF SIMD Floating-point exception
DEF_ISR_STUB(0x14);         // #VE Virtualization exception
DEF_ISR_STUB(0x15);         // #CP Control protection exception
DEF_ISR_STUB(0x16);         // Reserved
DEF_ISR_STUB(0x17);         // Reserved
DEF_ISR_STUB(0x18);         // Reserved
DEF_ISR_STUB(0x19);         // Reserved
DEF_ISR_STUB(0x1A);         // Reserved
DEF_ISR_STUB(0x1B);         // Reserved
DEF_ISR_STUB(0x1C);         // #HV Hypervisor injection exception
DEF_ISR_STUB(0x1D);         // #VC VMM communication exception
DEF_ISR_ERR_STUB(0x1E);     // #SX Security exception
DEF_ISR_STUB(0x1F);         // Reserved

// Hardware interrupts (IRQs) - 0x20-0x2F
DEF_ISR_STUB_IRQ(0x20); // Timer
DEF_ISR_STUB_IRQ(0x21); // Keyboard
DEF_ISR_STUB_IRQ(0x22);
DEF_ISR_STUB_IRQ(0x23);
DEF_ISR_STUB_IRQ(0x24);
DEF_ISR_STUB_IRQ(0x25);
DEF_ISR_STUB_IRQ(0x26);
DEF_ISR_STUB_IRQ(0x27);
DEF_ISR_STUB_IRQ(0x28);
DEF_ISR_STUB_IRQ(0x29);
DEF_ISR_STUB_IRQ(0x2A);
DEF_ISR_STUB_IRQ(0x2B);
DEF_ISR_STUB_IRQ(0x2C);
DEF_ISR_STUB_IRQ(0x2D);
DEF_ISR_STUB_IRQ(0x2E);
DEF_ISR_STUB_IRQ(0x2F);

// Remaining Interrupts (0x30-0xFF)
DEF_ISR_STUB(0x30); DEF_ISR_STUB(0x31); DEF_ISR_STUB(0x32); DEF_ISR_STUB(0x33);
DEF_ISR_STUB(0x34); DEF_ISR_STUB(0x35); DEF_ISR_STUB(0x36); DEF_ISR_STUB(0x37);
DEF_ISR_STUB(0x38); DEF_ISR_STUB(0x39); DEF_ISR_STUB(0x3A); DEF_ISR_STUB(0x3B);
DEF_ISR_STUB(0x3C); DEF_ISR_STUB(0x3D); DEF_ISR_STUB(0x3E); DEF_ISR_STUB(0x3F);
DEF_ISR_STUB(0x40); DEF_ISR_STUB(0x41); DEF_ISR_STUB(0x42); DEF_ISR_STUB(0x43);
DEF_ISR_STUB(0x44); DEF_ISR_STUB(0x45); DEF_ISR_STUB(0x46); DEF_ISR_STUB(0x47);
DEF_ISR_STUB(0x48); DEF_ISR_STUB(0x49); DEF_ISR_STUB(0x4A); DEF_ISR_STUB(0x4B);
DEF_ISR_STUB(0x4C); DEF_ISR_STUB(0x4D); DEF_ISR_STUB(0x4E); DEF_ISR_STUB(0x4F);
DEF_ISR_STUB(0x50); DEF_ISR_STUB(0x51); DEF_ISR_STUB(0x52); DEF_ISR_STUB(0x53);
DEF_ISR_STUB(0x54); DEF_ISR_STUB(0x55); DEF_ISR_STUB(0x56); DEF_ISR_STUB(0x57);
DEF_ISR_STUB(0x58); DEF_ISR_STUB(0x59); DEF_ISR_STUB(0x5A); DEF_ISR_STUB(0x5B);
DEF_ISR_STUB(0x5C); DEF_ISR_STUB(0x5D); DEF_ISR_STUB(0x5E); DEF_ISR_STUB(0x5F);
DEF_ISR_STUB(0x60); DEF_ISR_STUB(0x61); DEF_ISR_STUB(0x62); DEF_ISR_STUB(0x63);
DEF_ISR_STUB(0x64); DEF_ISR_STUB(0x65); DEF_ISR_STUB(0x66); DEF_ISR_STUB(0x67);
DEF_ISR_STUB(0x68); DEF_ISR_STUB(0x69); DEF_ISR_STUB(0x6A); DEF_ISR_STUB(0x6B);
DEF_ISR_STUB(0x6C); DEF_ISR_STUB(0x6D); DEF_ISR_STUB(0x6E); DEF_ISR_STUB(0x6F);
DEF_ISR_STUB(0x70); DEF_ISR_STUB(0x71); DEF_ISR_STUB(0x72); DEF_ISR_STUB(0x73);
DEF_ISR_STUB(0x74); DEF_ISR_STUB(0x75); DEF_ISR_STUB(0x76); DEF_ISR_STUB(0x77);
DEF_ISR_STUB(0x78); DEF_ISR_STUB(0x79); DEF_ISR_STUB(0x7A); DEF_ISR_STUB(0x7B);
DEF_ISR_STUB(0x7C); DEF_ISR_STUB(0x7D); DEF_ISR_STUB(0x7E); DEF_ISR_STUB(0x7F);
DEF_ISR_STUB(0x80); DEF_ISR_STUB(0x81); DEF_ISR_STUB(0x82); DEF_ISR_STUB(0x83);
DEF_ISR_STUB(0x84); DEF_ISR_STUB(0x85); DEF_ISR_STUB(0x86); DEF_ISR_STUB(0x87);
DEF_ISR_STUB(0x88); DEF_ISR_STUB(0x89); DEF_ISR_STUB(0x8A); DEF_ISR_STUB(0x8B);
DEF_ISR_STUB(0x8C); DEF_ISR_STUB(0x8D); DEF_ISR_STUB(0x8E); DEF_ISR_STUB(0x8F);
DEF_ISR_STUB(0x90); DEF_ISR_STUB(0x91); DEF_ISR_STUB(0x92); DEF_ISR_STUB(0x93);
DEF_ISR_STUB(0x94); DEF_ISR_STUB(0x95); DEF_ISR_STUB(0x96); DEF_ISR_STUB(0x97);
DEF_ISR_STUB(0x98); DEF_ISR_STUB(0x99); DEF_ISR_STUB(0x9A); DEF_ISR_STUB(0x9B);
DEF_ISR_STUB(0x9C); DEF_ISR_STUB(0x9D); DEF_ISR_STUB(0x9E); DEF_ISR_STUB(0x9F);
DEF_ISR_STUB(0xA0); DEF_ISR_STUB(0xA1); DEF_ISR_STUB(0xA2); DEF_ISR_STUB(0xA3);
DEF_ISR_STUB(0xA4); DEF_ISR_STUB(0xA5); DEF_ISR_STUB(0xA6); DEF_ISR_STUB(0xA7);
DEF_ISR_STUB(0xA8); DEF_ISR_STUB(0xA9); DEF_ISR_STUB(0xAA); DEF_ISR_STUB(0xAB);
DEF_ISR_STUB(0xAC); DEF_ISR_STUB(0xAD); DEF_ISR_STUB(0xAE); DEF_ISR_STUB(0xAF);
DEF_ISR_STUB(0xB0); DEF_ISR_STUB(0xB1); DEF_ISR_STUB(0xB2); DEF_ISR_STUB(0xB3);
DEF_ISR_STUB(0xB4); DEF_ISR_STUB(0xB5); DEF_ISR_STUB(0xB6); DEF_ISR_STUB(0xB7);
DEF_ISR_STUB(0xB8); DEF_ISR_STUB(0xB9); DEF_ISR_STUB(0xBA); DEF_ISR_STUB(0xBB);
DEF_ISR_STUB(0xBC); DEF_ISR_STUB(0xBD); DEF_ISR_STUB(0xBE); DEF_ISR_STUB(0xBF);
DEF_ISR_STUB(0xC0); DEF_ISR_STUB(0xC1); DEF_ISR_STUB(0xC2); DEF_ISR_STUB(0xC3);
DEF_ISR_STUB(0xC4); DEF_ISR_STUB(0xC5); DEF_ISR_STUB(0xC6); DEF_ISR_STUB(0xC7);
DEF_ISR_STUB(0xC8); DEF_ISR_STUB(0xC9); DEF_ISR_STUB(0xCA); DEF_ISR_STUB(0xCB);
DEF_ISR_STUB(0xCC); DEF_ISR_STUB(0xCD); DEF_ISR_STUB(0xCE); DEF_ISR_STUB(0xCF);
DEF_ISR_STUB(0xD0); DEF_ISR_STUB(0xD1); DEF_ISR_STUB(0xD2); DEF_ISR_STUB(0xD3);
DEF_ISR_STUB(0xD4); DEF_ISR_STUB(0xD5); DEF_ISR_STUB(0xD6); DEF_ISR_STUB(0xD7);
DEF_ISR_STUB(0xD8); DEF_ISR_STUB(0xD9); DEF_ISR_STUB(0xDA); DEF_ISR_STUB(0xDB);
DEF_ISR_STUB(0xDC); DEF_ISR_STUB(0xDD); DEF_ISR_STUB(0xDE); DEF_ISR_STUB(0xDF);
DEF_ISR_STUB(0xE0); DEF_ISR_STUB(0xE1); DEF_ISR_STUB(0xE2); DEF_ISR_STUB(0xE3);
DEF_ISR_STUB(0xE4); DEF_ISR_STUB(0xE5); DEF_ISR_STUB(0xE6); DEF_ISR_STUB(0xE7);
DEF_ISR_STUB(0xE8); DEF_ISR_STUB(0xE9); DEF_ISR_STUB(0xEA); DEF_ISR_STUB(0xEB);
DEF_ISR_STUB(0xEC); DEF_ISR_STUB(0xED); DEF_ISR_STUB(0xEE); DEF_ISR_STUB(0xEF);
DEF_ISR_STUB(0xF0); DEF_ISR_STUB(0xF1); DEF_ISR_STUB(0xF2); DEF_ISR_STUB(0xF3);
DEF_ISR_STUB(0xF4); DEF_ISR_STUB(0xF5); DEF_ISR_STUB(0xF6); DEF_ISR_STUB(0xF7);
DEF_ISR_STUB(0xF8); DEF_ISR_STUB(0xF9); DEF_ISR_STUB(0xFA); DEF_ISR_STUB(0xFB);
DEF_ISR_STUB(0xFC); DEF_ISR_STUB(0xFD); DEF_ISR_STUB(0xFE); DEF_ISR_STUB(0xFF);